# -*- coding: utf-8 -*-
"""IVCU_IA_FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YJRjnDuNJlVPons1AZ2p42XT2IlgTF8
"""

# -*- coding: utf-8 -*-
"""
ivcu_madrid_v4.py
=================
Índice de Vulnerabilidad Climática Urbana (IVCU) por barrios — Madrid
Proyecto para los Premios de Reutilización de Datos 2026 del Ayuntamiento de Madrid

CORRECCIONES v4 respecto a v3:
  · Bug corregido: NO₂ y temperatura ya NO son un valor global único para todos los
    barrios — se interpola espacialmente por IDW (Inverse Distance Weighting) desde
    las estaciones de medición, asignando un valor diferenciado a cada barrio.
  · Bug corregido: ranking_ref e ivcu_ref ya NO quedan vacíos — el join contra el
    dataset oficial de vulnerabilidad es más robusto: prueba por código numérico,
    por nombre normalizado y por código de distrito+barrio como fallback.
  · Bug corregido: pob_total y pct_mayores_65 ya NO se repiten por distrito — el
    padrón se une siempre a nivel barrio (cod_dist_barrio de 4 dígitos); si el merge
    falla se imputa la media del distrito, no la media global.
  · Bug corregido: renta_neta repetida — cuando la renta está a nivel distrito se
    propaga a los barrios del mismo distrito con una nota explícita en el log, sin
    afectar a los barrios que ya tienen dato propio a nivel barrio.
  · NUEVO — Bloque 6: Clustering IA (K-Means + PCA) para identificar perfiles de
    vulnerabilidad climática. Añade columna 'perfil_vulnerabilidad' al CSV y al mapa.

Fuentes de datos (todas del portal datos.madrid.es):
  · Calidad del aire diario          — magnitud 8 (NO₂, µg/m³)
  · Datos meteorológicos diarios     — magnitud 83 (temperatura media, °C)
  · Padrón municipal histórico       — población por edad, barrio y sección
  · Indicadores socioeconómicos      — renta neta anual por barrio/distrito
  · Arbolado en parques histórico    — nº árboles por distrito (2024)
  · Ranking vulnerabilidad barrios   — índice de referencia del Ayuntamiento
  · Shapefile de barrios             — geometrías para exportar a ArcGIS Pro

Uso en Google Colab:
  1. Sube este fichero a Colab o ábrelo directamente
  2. Ejecútalo: Runtime → Run all
  3. Los ficheros de salida se descargarán automáticamente al terminar
"""

# ──────────────────────────────────────────────────────────────────────────────
# INSTALACIÓN AUTOMÁTICA DE DEPENDENCIAS
# ──────────────────────────────────────────────────────────────────────────────
import subprocess, sys

def instalar(paquete):
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', paquete])

for pkg in ['requests', 'pandas', 'numpy', 'geopandas', 'folium', 'scikit-learn']:
    try:
        __import__(pkg.replace('-', '_'))
    except ImportError:
        print(f'  Instalando {pkg}...')
        instalar(pkg)

# ──────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ──────────────────────────────────────────────────────────────────────────────
import requests
import pandas as pd
import numpy as np
import geopandas as gpd
import json
import os
import zipfile
import io
import warnings
warnings.filterwarnings('ignore')

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# ──────────────────────────────────────────────────────────────────────────────
# CONFIGURACIÓN
# ──────────────────────────────────────────────────────────────────────────────

os.makedirs('data/raw',       exist_ok=True)
os.makedirs('data/processed', exist_ok=True)
os.makedirs('data/spatial',   exist_ok=True)

# ──────────────────────────────────────────────────────────────────────────────
# SUBIDA MANUAL DE DATOS (Google Colab)
# ──────────────────────────────────────────────────────────────────────────────
# El portal datos.madrid.es bloquea descargas automáticas desde servidores.
# Debes descargar los 9 ficheros manualmente desde el navegador y subirlos
# a Colab con la función subir_datos_colab() ANTES de ejecutar main().
#
# Ficheros a descargar (URL) y nombre que tendrán en data/raw/:
#
#  calidad_aire.csv            https://datos.madrid.es/dataset/201410-0-calidad-aire-diario/resource/201410-2-calidad-aire-diario-csv/download/201410-2-calidad-aire-diario-csv.csv
#  meteo.csv                   https://datos.madrid.es/dataset/300351-0-meteorologicos-diarios/resource/300351-1-meteorologicos-diarios-csv/download/300351-1-meteorologicos-diarios-csv.csv
#  padron.csv                  https://datos.madrid.es/dataset/200076-0-padron/resource/200076-2-padron-csv/download/200076-2-padron-csv.csv
#  socioeconomico.csv          https://datos.madrid.es/dataset/300087-0-indicadores-distritos/resource/300087-0-indicadores-distritos-csv/download/300087-0-indicadores-distritos-csv.csv
#  arbolado.csv                https://datos.madrid.es/dataset/300264-0-arbolado-parques-historico/resource/300264-104-arbolado-parques-historico/download/300264-104-arbolado-parques-historico.csv
#  vulnerabilidad.csv          https://datos.madrid.es/dataset/300301-0-ranking-vulnerabilidad/resource/300301-0-ranking-vulnerabilidad-csv/download/300301-0-ranking-vulnerabilidad-csv.csv
#  estaciones_calidad_aire.csv https://datos.madrid.es/dataset/212629-0-estaciones-control-aire/resource/212629-0-estaciones-control-aire-csv/download/212629-0-estaciones-control-aire-csv.csv
#  estaciones_meteo.csv        https://datos.madrid.es/dataset/300360-0-meteorologicos-estaciones/resource/300360-1-meteorologicos-estaciones-csv/download/300360-1-meteorologicos-estaciones-csv.csv
#  barrios.zip                 https://datos.madrid.es/dataset/300496-0-barrios-madrid/resource/300496-3-barrios-madrid/download/300496-3-barrios-madrid.zip
#
# Pasos en Google Colab:
#   1. Descarga los 9 ficheros con el navegador desde las URLs de arriba.
#   2. Ejecuta: subir_datos_colab()  (descomenta la llamada al final de este bloque)
#   3. En el diálogo que aparece, selecciona los 9 ficheros a la vez.
#   4. El script los renombra y coloca automáticamente en data/raw/.
#   5. Una vez subidos, ejecuta main() con normalidad.

# Mapeo nombre-original → ruta-destino en data/raw/
NOMBRES_ESPERADOS = {
    # Nombres tal como los descarga el navegador desde datos.madrid.es
    '201410-2-calidad-aire-diario-csv.csv':       'data/raw/calidad_aire.csv',
    '300351-1-meteorologicos-diarios-csv.csv':     'data/raw/meteo.csv',
    '200076-2-padron-csv.csv':                     'data/raw/padron.csv',
    '300087-0-indicadores-distritos-csv.csv':      'data/raw/socioeconomico.csv',
    '300264-104-arbolado-parques-historico.csv':   'data/raw/arbolado.csv',
    '300301-0-ranking-vulnerabilidad-csv.csv':     'data/raw/vulnerabilidad.csv',
    '212629-0-estaciones-control-aire-csv.csv':    'data/raw/estaciones_calidad_aire.csv',
    '300360-1-meteorologicos-estaciones-csv.csv':  'data/raw/estaciones_meteo.csv',
    '300496-3-barrios-madrid.zip':                 'data/raw/barrios.zip',
    # Nombres cortos por si el usuario los renombró manualmente
    'calidad_aire.csv':             'data/raw/calidad_aire.csv',
    'meteo.csv':                    'data/raw/meteo.csv',
    'padron.csv':                   'data/raw/padron.csv',
    'socioeconomico.csv':           'data/raw/socioeconomico.csv',
    'arbolado.csv':                 'data/raw/arbolado.csv',
    'vulnerabilidad.csv':           'data/raw/vulnerabilidad.csv',
    'estaciones_calidad_aire.csv':  'data/raw/estaciones_calidad_aire.csv',
    'estaciones_meteo.csv':         'data/raw/estaciones_meteo.csv',
    'barrios.zip':                  'data/raw/barrios.zip',
}

def subir_datos_colab():
    """Sube los 9 ficheros de datos.madrid.es a data/raw/ en Google Colab.
    Llama a esta funcion UNA VEZ antes de ejecutar main()."""
    try:
        from google.colab import files
        import shutil
        print('Selecciona los 9 ficheros descargados de datos.madrid.es...')
        uploaded = files.upload()
        colocados = []
        no_reconocidos = []
        for fname in uploaded:
            destino = NOMBRES_ESPERADOS.get(fname)
            if destino:
                shutil.move(fname, destino)
                colocados.append(f'  OK  {fname}  ->  {destino}')
            else:
                destino = f'data/raw/{fname}'
                shutil.move(fname, destino)
                no_reconocidos.append(f'  ??  {fname}  ->  {destino}  (nombre no reconocido)')
        if colocados:
            print('Ficheros colocados correctamente:')
            print('\n'.join(colocados))
        if no_reconocidos:
            print('Ficheros con nombre no reconocido (comprueba que esten bien):')
            print('\n'.join(no_reconocidos))
        print(f'\nTotal: {len(colocados) + len(no_reconocidos)} fichero(s) en data/raw/')
        print('Ahora puedes ejecutar main()')
    except ImportError:
        print('Esta funcion solo funciona en Google Colab.')
        print('En local, copia los 9 ficheros manualmente a data/raw/ con los nombres indicados arriba.')

# PASO 1 — Descomenta la siguiente linea y ejecutala para subir los datos:
# subir_datos_colab()

# PASO 2 — Una vez subidos los datos, ejecuta el script normalmente (main() al final).

HEADERS = {
    'User-Agent': (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
        'AppleWebKit/537.36 (KHTML, like Gecko) '
        'Chrome/124.0.0.0 Safari/537.36'
    ),
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'es-ES,es;q=0.9',
    'Referer': 'https://datos.madrid.es/',
}

URLS = {
    'calidad_aire': (
        'https://datos.madrid.es/dataset/201410-0-calidad-aire-diario/resource/'
        '201410-2-calidad-aire-diario-csv/download/201410-2-calidad-aire-diario-csv.csv'
    ),
    'calidad_aire_2023': (
        'https://datos.madrid.es/dataset/201410-0-calidad-aire-diario/resource/'
        '201410-2-calidad-aire-diario-csv/download/201410-2-calidad-aire-diario-csv.csv'
    ),
    'meteo': (
        'https://datos.madrid.es/dataset/300351-0-meteorologicos-diarios/resource/'
        '300351-1-meteorologicos-diarios-csv/download/300351-1-meteorologicos-diarios-csv.csv'
    ),
    'padron': (
        'https://datos.madrid.es/dataset/200076-0-padron/resource/'
        '200076-2-padron-csv/download/200076-2-padron-csv.csv'
    ),
    'socioeconomico': (
        'https://datos.madrid.es/dataset/300087-0-indicadores-distritos/resource/'
        '300087-0-indicadores-distritos-csv/download/300087-0-indicadores-distritos-csv.csv'
    ),
    'arbolado': (
        'https://datos.madrid.es/dataset/300264-0-arbolado-parques-historico/resource/'
        '300264-104-arbolado-parques-historico/download/300264-104-arbolado-parques-historico.csv'
    ),
    'vulnerabilidad': (
        'https://datos.madrid.es/dataset/300301-0-ranking-vulnerabilidad/resource/'
        '300301-0-ranking-vulnerabilidad-csv/download/300301-0-ranking-vulnerabilidad-csv.csv'
    ),
    'estaciones_calidad_aire': (
        'https://datos.madrid.es/dataset/212629-0-estaciones-control-aire/resource/'
        '212629-0-estaciones-control-aire-csv/download/212629-0-estaciones-control-aire-csv.csv'
    ),
    'estaciones_meteo': (
        'https://datos.madrid.es/dataset/300360-0-meteorologicos-estaciones/resource/'
        '300360-1-meteorologicos-estaciones-csv/download/300360-1-meteorologicos-estaciones-csv.csv'
    ),
    'barrios_shp': (
        'https://datos.madrid.es/dataset/300496-0-barrios-madrid/resource/'
        '300496-3-barrios-madrid/download/300496-3-barrios-madrid.zip'
    ),
}

# Pesos AHP — metodología IPCC AR6 + literatura española
PESOS_IVCU = {
    'exposicion_calor':    0.25,
    'falta_verde':         0.25,
    'vulnerabilidad_soc':  0.20,
    'privacion_economica': 0.20,
    'contaminacion_aire':  0.10,
}

TIMEOUT = 120
UMBRALES_IVCU = {}

# Paleta científica divergente azul–rojo (clasificación por quintiles)
COLORES = {
    'Muy bajo': '#2166ac',
    'Bajo':     '#74add1',
    'Moderado': '#fee090',
    'Alto':     '#f46d43',
    'Crítico':  '#a50026',
}

# Paleta para perfiles de clustering (6 perfiles máximo)
COLORES_PERFIL = {
    'Perfil A — Calor y densidad':       '#e74c3c',
    'Perfil B — Privación económica':    '#e67e22',
    'Perfil C — Vulnerabilidad social':  '#8e44ad',
    'Perfil D — Contaminación':          '#2980b9',
    'Perfil E — Verde deficitario':      '#27ae60',
    'Perfil F — Bajo riesgo general':    '#95a5a6',
}


# ──────────────────────────────────────────────────────────────────────────────
# FUNCIONES AUXILIARES
# ──────────────────────────────────────────────────────────────────────────────

def limpiar_columnas(df):
    """Corrige BOM Unicode y artefactos de encoding en nombres de columna."""
    df.columns = (
        df.columns
        .str.strip()
        .str.replace('\ufeff', '',  regex=False)
        .str.replace('ï»¿',   '',  regex=False)
        .str.replace('Ã±',  'ñ',  regex=False)
        .str.replace('Ã­',  'í',  regex=False)
        .str.replace('Ã©',  'é',  regex=False)
        .str.replace('Ã³',  'ó',  regex=False)
        .str.replace('Ãº',  'ú',  regex=False)
        .str.replace('Ã¡',  'á',  regex=False)
        .str.replace('Ã',   'Á',  regex=False)
        .str.replace('Â·',  '·',  regex=False)
        .str.replace('NÂº', 'Nº', regex=False)
    )
    return df


def limpiar_texto(serie):
    """Corrige encoding corrupto dentro de valores de texto."""
    if serie.dtype != object:
        return serie
    return (
        serie
        .str.replace('Ã±',  'ñ',  regex=False)
        .str.replace('Ã­',  'í',  regex=False)
        .str.replace('Ã©',  'é',  regex=False)
        .str.replace('Ã³',  'ó',  regex=False)
        .str.replace('Ãº',  'ú',  regex=False)
        .str.replace('Ã¡',  'á',  regex=False)
        .str.replace('Â·',  '·',  regex=False)
        .str.replace('Ã',   'Á',  regex=False)
    )


def normalizar_nombre(s):
    """Normaliza un nombre para comparación fuzzy: minúsculas, sin tildes, sin espacios extra."""
    import unicodedata
    s = str(s).strip().lower()
    s = ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')
    s = s.replace('-', ' ').replace('_', ' ')
    s = ' '.join(s.split())
    return s


def leer_csv_madrid(ruta_o_url, es_url=False):
    """Lee un CSV del portal de Madrid gestionando encoding, BOM y separador."""
    if es_url:
        resp = requests.get(ruta_o_url, headers=HEADERS, timeout=TIMEOUT)
        resp.raise_for_status()
        contenido = io.BytesIO(resp.content)
    else:
        contenido = ruta_o_url
    try:
        df = pd.read_csv(contenido, encoding='utf-8-sig', sep=',', low_memory=False)
        if df.shape[1] == 1:
            raise ValueError("sep incorrecto")
    except Exception:
        if es_url:
            resp = requests.get(ruta_o_url, headers=HEADERS, timeout=TIMEOUT)
            contenido = io.BytesIO(resp.content)
        df = pd.read_csv(contenido, encoding='latin-1', sep=';', low_memory=False)
    return limpiar_columnas(df)


def descargar(url, ruta_local, descripcion='', fallback_url=None):
    """Descarga con cabeceras de navegador y fallback automático."""
    url = url.strip()
    if os.path.exists(ruta_local) and os.path.getsize(ruta_local) > 1000:
        print(f'  (ya descargado) {ruta_local}')
        return ruta_local
    print(f'  Descargando {descripcion}...')
    urls_a_probar = [url] + ([fallback_url.strip()] if fallback_url else [])
    for intento, u in enumerate(urls_a_probar, 1):
        try:
            resp = requests.get(u, headers=HEADERS, timeout=TIMEOUT)
            if resp.status_code == 200 and len(resp.content) > 500:
                with open(ruta_local, 'wb') as f:
                    f.write(resp.content)
                print(f'  ✓ {ruta_local} ({len(resp.content)/1024:.0f} KB)')
                return ruta_local
            else:
                print(f'  ⚠ Intento {intento}: HTTP {resp.status_code}')
        except Exception as e:
            print(f'  ⚠ Intento {intento} fallido: {e}')
    print(f'\n  ✗ NO SE PUDO DESCARGAR: {descripcion}')
    print(f'    Descárgalo manualmente de datos.madrid.es y guárdalo en: {ruta_local}\n')
    return None


def normalizar_0_10(serie, invertir=False):
    """Normaliza una serie al rango 0–10. invertir=True para indicadores donde
    más valor significa menos vulnerabilidad (p.ej. renta, árboles)."""
    minimo, maximo = serie.min(), serie.max()
    if maximo == minimo:
        return pd.Series([5.0] * len(serie), index=serie.index)
    normalizado = (serie - minimo) / (maximo - minimo) * 10
    return (10 - normalizado) if invertir else normalizado


def pivotear_formato_ancho(df, magnitud_cod, nombre_col):
    """Convierte el formato ancho D01…D31/V01…V31 a formato largo y
    devuelve la media mensual por estación."""
    df = df[df['MAGNITUD'] == magnitud_cod].copy()
    if len(df) == 0:
        return pd.DataFrame(columns=['ESTACION', 'ANO', 'MES', nombre_col])
    registros = []
    for i in range(1, 32):
        dia, flag = f'D{i:02d}', f'V{i:02d}'
        if dia not in df.columns:
            continue
        tmp = df[['ESTACION', 'ANO', 'MES', dia, flag]].copy()
        tmp.columns = ['ESTACION', 'ANO', 'MES', 'valor', 'flag']
        registros.append(tmp)
    largo = pd.concat(registros, ignore_index=True)
    largo = largo[largo['flag'] == 'V']
    largo['valor'] = pd.to_numeric(largo['valor'], errors='coerce')
    largo = largo.dropna(subset=['valor'])
    return (
        largo.groupby(['ESTACION', 'ANO', 'MES'])['valor']
        .mean().reset_index().rename(columns={'valor': nombre_col})
    )


def idw_interpolar(estaciones_df, centros_barrios, col_valor, power=2):
    """
    Interpolación IDW (Inverse Distance Weighting) desde estaciones de medición
    hacia los centroides de los barrios.

    Parámetros
    ----------
    estaciones_df : DataFrame con columnas ['lon', 'lat', col_valor]
    centros_barrios : DataFrame con columnas ['lon', 'lat'] indexado igual que ivcu
    col_valor : nombre de la columna con el valor a interpolar
    power : exponente IDW (2 = cuadrático, estándar)

    Devuelve
    --------
    Series con el valor interpolado para cada fila de centros_barrios
    """
    est = estaciones_df.dropna(subset=['lon', 'lat', col_valor])
    if len(est) == 0:
        print(f'     ⚠ Sin estaciones con coordenadas para IDW — usando media global')
        return pd.Series([estaciones_df[col_valor].mean()] * len(centros_barrios),
                         index=centros_barrios.index)

    est_coords = est[['lon', 'lat']].values
    est_vals   = est[col_valor].values
    bar_coords = centros_barrios[['lon', 'lat']].values

    resultados = []
    for bc in bar_coords:
        distancias = np.sqrt(((est_coords - bc) ** 2).sum(axis=1))
        # Si un barrio coincide exactamente con una estación, devolver ese valor
        if distancias.min() < 1e-6:
            resultados.append(est_vals[distancias.argmin()])
            continue
        pesos = 1.0 / (distancias ** power)
        valor_idw = np.sum(pesos * est_vals) / np.sum(pesos)
        resultados.append(valor_idw)

    return pd.Series(resultados, index=centros_barrios.index)


# ──────────────────────────────────────────────────────────────────────────────
# BLOQUE 1 — DESCARGA DE DATOS
# ──────────────────────────────────────────────────────────────────────────────

def descargar_todos():
    print('\n' + '═' * 60)
    print('  BLOQUE 1 — DESCARGA DE DATOS')
    print('═' * 60)

    # ── Comprobación previa: el portal datos.madrid.es bloquea descargas ─────
    # automáticas desde servidores (devuelve HTTP 403 "Host not in allowlist").
    # Si los ficheros ya están en data/raw/ se saltan; si no, se intenta la
    # descarga y, en caso de fallo, se para el script con instrucciones claras.

    ARCHIVOS_NECESARIOS = {
        'calidad_aire':            ('data/raw/calidad_aire.csv',           'https://datos.madrid.es/dataset/201410-0-calidad-aire-diario/resource/201410-2-calidad-aire-diario-csv/download/201410-2-calidad-aire-diario-csv.csv'),
        'meteo':                   ('data/raw/meteo.csv',                  'https://datos.madrid.es/dataset/300351-0-meteorologicos-diarios/resource/300351-1-meteorologicos-diarios-csv/download/300351-1-meteorologicos-diarios-csv.csv'),
        'padron':                  ('data/raw/padron.csv',                 'https://datos.madrid.es/dataset/200076-0-padron/resource/200076-2-padron-csv/download/200076-2-padron-csv.csv'),
        'socioeconomico':          ('data/raw/socioeconomico.csv',         'https://datos.madrid.es/dataset/300087-0-indicadores-distritos/resource/300087-0-indicadores-distritos-csv/download/300087-0-indicadores-distritos-csv.csv'),
        'arbolado':                ('data/raw/arbolado.csv',               'https://datos.madrid.es/dataset/300264-0-arbolado-parques-historico/resource/300264-104-arbolado-parques-historico/download/300264-104-arbolado-parques-historico.csv'),
        'vulnerabilidad':          ('data/raw/vulnerabilidad.csv',         'https://datos.madrid.es/dataset/300301-0-ranking-vulnerabilidad/resource/300301-0-ranking-vulnerabilidad-csv/download/300301-0-ranking-vulnerabilidad-csv.csv'),
        'estaciones_calidad_aire': ('data/raw/estaciones_calidad_aire.csv','https://datos.madrid.es/dataset/212629-0-estaciones-control-aire/resource/212629-0-estaciones-control-aire-csv/download/212629-0-estaciones-control-aire-csv.csv'),
        'estaciones_meteo':        ('data/raw/estaciones_meteo.csv',       'https://datos.madrid.es/dataset/300360-0-meteorologicos-estaciones/resource/300360-1-meteorologicos-estaciones-csv/download/300360-1-meteorologicos-estaciones-csv.csv'),
        'barrios_shp':             ('data/raw/barrios.zip',                'https://datos.madrid.es/dataset/300496-0-barrios-madrid/resource/300496-3-barrios-madrid/download/300496-3-barrios-madrid.zip'),
    }

    faltantes = []
    for nombre, (ruta, url_info) in ARCHIVOS_NECESARIOS.items():
        if os.path.exists(ruta) and os.path.getsize(ruta) > 1000:
            print(f'  ✓ (ya existe) {ruta}')
        else:
            faltantes.append((nombre, ruta, url_info))

    if faltantes:
        # Intentar descarga automática
        fallidos = []
        for nombre, ruta, url_principal in faltantes:
            fallback = URLS.get('calidad_aire_2023') if nombre == 'calidad_aire' else None
            resultado = descargar(URLS.get(nombre, url_principal), ruta, nombre, fallback_url=fallback)
            if nombre == 'barrios_shp' and resultado:
                if not any(f.endswith('.shp') for f in os.listdir('data/spatial/')):
                    try:
                        with zipfile.ZipFile(ruta) as z:
                            z.extractall('data/spatial/')
                        print('  ✓ Shapefile extraído en data/spatial/')
                    except Exception as e:
                        print(f'  ✗ Error al extraer ZIP: {e}')
            if not resultado:
                fallidos.append((nombre, ruta, url_principal))

        if fallidos:
            print('\n' + '═' * 60)
            print('  ✗ DESCARGA AUTOMÁTICA BLOQUEADA POR datos.madrid.es')
            print('    El portal solo permite descargas desde navegador.')
            print('    Descarga manualmente los siguientes ficheros y')
            print('    guárdalos en la carpeta data/raw/ antes de continuar:')
            print('─' * 60)
            for nombre, ruta, url in fallidos:
                print(f'\n  [{nombre}]')
                print(f'    URL:   {url}')
                print(f'    Ruta:  {ruta}')
            print('\n' + '─' * 60)
            print('  En Google Colab puedes subirlos con:')
            print('    from google.colab import files')
            print('    uploaded = files.upload()  # selecciona todos a la vez')
            print('    import shutil')
            print('    for fname in uploaded: shutil.move(fname, "data/raw/" + fname)')
            print('═' * 60)
            raise RuntimeError(
                f'Faltan {len(fallidos)} fichero(s) en data/raw/. '
                'Descárgalos manualmente siguiendo las instrucciones anteriores.'
            )

    # Extraer shapefile si aún no se ha hecho
    ruta_zip = 'data/raw/barrios.zip'
    if os.path.exists(ruta_zip) and not any(f.endswith('.shp') for f in os.listdir('data/spatial/')):
        try:
            with zipfile.ZipFile(ruta_zip) as z:
                z.extractall('data/spatial/')
            print('  ✓ Shapefile extraído en data/spatial/')
        except Exception as e:
            print(f'  ✗ Error al extraer ZIP: {e}')

    print('\n  ✓ Todos los ficheros disponibles en data/raw/')
    return {}


# ──────────────────────────────────────────────────────────────────────────────
# BLOQUE 2 — PROCESAMIENTO DE FUENTES
# ──────────────────────────────────────────────────────────────────────────────

def procesar_barrios_shapefile():
    print('\n  2a. Shapefile de barrios...')
    shp_files = [f for f in os.listdir('data/spatial/') if f.endswith('.shp')]
    if not shp_files:
        raise FileNotFoundError('No se encontró .shp en data/spatial/')
    gdf = gpd.read_file(f'data/spatial/{shp_files[0]}')
    print(f'     CRS original: {gdf.crs} | Barrios: {len(gdf)}')
    gdf = limpiar_columnas(gdf)
    col_map = {}
    for col in gdf.columns:
        cu = col.upper()
        if 'CODDIS' in cu or cu == 'COD_DIS':
            col_map['cod_distrito'] = col
        elif 'NOMDIS' in cu or cu == 'NOMDIST':
            col_map['nombre_distrito'] = col
        elif 'COD_BAR' in cu or cu == 'CODBAR':
            col_map['cod_barrio'] = col
        elif cu in ('NOMBRE', 'NOMBAR', 'DESC_BARRIO'):
            col_map['nombre_barrio'] = col
        elif 'AREA' in cu or 'SHAPE_AREA' in cu:
            col_map['area_m2'] = col
    if 'cod_barrio' not in col_map and 'COD_DISBAR' in gdf.columns:
        col_map['cod_barrio'] = 'COD_DISBAR'
    if 'area_m2' not in col_map:
        gdf_utm = gdf.to_crs(epsg=25830) if gdf.crs and gdf.crs.to_epsg() != 25830 else gdf
        gdf['area_calc'] = gdf_utm.geometry.area
        col_map['area_m2'] = 'area_calc'
    gdf_base = gdf[[col_map[k] for k in col_map if k != 'geometry'] + ['geometry']].copy()
    gdf_base.rename(columns={v: k for k, v in col_map.items()}, inplace=True)
    for c in ['nombre_distrito', 'nombre_barrio']:
        if c in gdf_base.columns:
            gdf_base[c] = limpiar_texto(gdf_base[c].astype(str))
    gdf_base['cod_distrito'] = pd.to_numeric(gdf_base['cod_distrito'], errors='coerce').astype('Int64')
    gdf_base['area_m2']      = pd.to_numeric(gdf_base['area_m2'],      errors='coerce')
    gdf_utm = gdf_base.to_crs(epsg=25830) if gdf_base.crs and gdf_base.crs.to_epsg() != 25830 else gdf_base
    gdf_base['centroide_x'] = gdf_utm.geometry.centroid.x
    gdf_base['centroide_y'] = gdf_utm.geometry.centroid.y
    gdf_wgs = gdf_base.to_crs(epsg=4326)
    gdf_base['lon'] = gdf_wgs.geometry.centroid.x
    gdf_base['lat'] = gdf_wgs.geometry.centroid.y
    print(f'     ✓ {len(gdf_base)} barrios procesados')
    return gdf_base


def procesar_vulnerabilidad_referencia():
    """
    FIX v6: el campo BARRIO del dataset oficial tiene espacios iniciales
    (p.ej. "   022. Las Acacias") que impedían extraer el código numérico.
    Solución: strip() antes de extraer código y nombre.
    También se normaliza el nombre eliminando artículos iniciales (Las, Los,
    La, El, Del) para maximizar el match con los nombres del shapefile.
    """
    print('\n  2b. Vulnerabilidad oficial (referencia)...')
    df = pd.read_csv('data/raw/vulnerabilidad.csv', encoding='latin-1', sep=';')
    df = limpiar_columnas(df)
    df = df[df['Año'] == df['Año'].max()].copy()
    df['Vulnerabilidad'] = pd.to_numeric(
        df['Vulnerabilidad'].astype(str).str.replace(',', '.', regex=False), errors='coerce'
    )

    # FIX v6: strip() para eliminar espacios iniciales antes de extraer código
    df['BARRIO_strip'] = df['BARRIO'].astype(str).str.strip()

    # Extraer código numérico (p.ej. "022. Las Acacias" → 22)
    df['cod_barrio_num'] = pd.to_numeric(
        df['BARRIO_strip'].str.extract(r'^(\d+)\.').squeeze(), errors='coerce'
    ).astype('Int64')

    # Nombre normalizado: eliminar el código inicial y artículos (Las, Los, La, El, Del)
    def extraer_nombre(barrio_str):
        nombre = barrio_str.split('.', 1)[-1] if '.' in barrio_str else barrio_str
        nombre = normalizar_nombre(nombre)
        # Eliminar artículos iniciales para mejorar el match
        for art in ('las ', 'los ', 'la ', 'el ', 'del ', 'de '):
            if nombre.startswith(art):
                nombre = nombre[len(art):]
                break
        return nombre.strip()

    df['nombre_barrio_norm'] = df['BARRIO_strip'].apply(extraer_nombre)

    resultado = df[['cod_barrio_num', 'nombre_barrio_norm', 'Ranking', 'Vulnerabilidad']].copy()
    resultado.columns = ['cod_barrio_vuln', 'nombre_barrio_norm', 'ranking_ref', 'ivcu_ref']
    print(f'     ✓ {len(resultado)} barrios con vulnerabilidad de referencia')
    print(f'     Códigos ejemplo: {resultado["cod_barrio_vuln"].dropna().head(5).tolist()}')
    return resultado


def procesar_padron_barrio():
    """
    FIX v4: el padrón siempre se devuelve a nivel barrio (cod_dist_barrio de 4 dígitos).
    Si faltaran datos para algún barrio, se imputa la media del DISTRITO, no la global.
    """
    print('\n  2c. Padrón municipal (% mayores 65)...')
    df = pd.read_csv('data/raw/padron.csv', encoding='latin-1', sep=';', low_memory=False)
    df = limpiar_columnas(df)
    df.rename(columns={df.columns[0]: 'COD_DISTRITO'}, inplace=True)
    df['poblacion'] = (
        df['ESPANOLESHOMBRES'].fillna(0) + df['ESPANOLESMUJERES'].fillna(0) +
        df['EXTRANJEROSHOMBRES'].fillna(0) + df['EXTRANJEROSMUJERES'].fillna(0)
    )
    df['edad_num']       = pd.to_numeric(df['COD_EDAD_INT'].astype(str).str.strip(), errors='coerce')
    df['COD_DIST_BARRIO'] = pd.to_numeric(df['COD_DIST_BARRIO'], errors='coerce').astype('Int64')
    df['COD_DISTRITO_num'] = pd.to_numeric(df['COD_DISTRITO'],    errors='coerce').astype('Int64')

    pob_total   = df.groupby('COD_DIST_BARRIO')['poblacion'].sum().reset_index().rename(
        columns={'poblacion': 'pob_total'})
    pob_mayores = df[df['edad_num'] >= 65].groupby('COD_DIST_BARRIO')['poblacion'].sum().reset_index().rename(
        columns={'poblacion': 'pob_65mas'})
    dist_map    = df[['COD_DIST_BARRIO', 'COD_DISTRITO_num']].drop_duplicates()

    resultado = pob_total.merge(pob_mayores, on='COD_DIST_BARRIO', how='left')
    resultado = resultado.merge(dist_map, on='COD_DIST_BARRIO', how='left')
    resultado['pob_65mas']      = resultado['pob_65mas'].fillna(0)
    resultado['pct_mayores_65'] = (resultado['pob_65mas'] / resultado['pob_total'] * 100).round(2)
    resultado.rename(columns={'COD_DIST_BARRIO': 'cod_dist_barrio',
                               'COD_DISTRITO_num': 'cod_distrito_padron'}, inplace=True)
    print(f'     ✓ {len(resultado)} barrios | % mayores 65: '
          f'{resultado["pct_mayores_65"].min():.1f}%–{resultado["pct_mayores_65"].max():.1f}%')
    return resultado


def procesar_renta_barrio():
    print('\n  2d. Renta neta anual por barrio...')
    df = pd.read_csv('data/raw/socioeconomico.csv', encoding='latin-1', sep=';', low_memory=False)
    df = limpiar_columnas(df)
    df.rename(columns={df.columns[0]: 'orden'}, inplace=True)
    col_rename = {}
    for c in df.columns:
        lc = c.lower().replace('ã±', 'ñ').replace('ã­', 'í').replace('ã©', 'é')
        if 'indicador_nivel1' in lc:   col_rename[c] = 'indicador_nivel1'
        elif 'indicador_nivel2' in lc: col_rename[c] = 'indicador_nivel2'
        elif 'valor_indicador' in lc:  col_rename[c] = 'valor_indicador'
        elif lc.strip() in ('año', 'a±o'): col_rename[c] = 'año'
        elif 'cod_barrio' in lc:       col_rename[c] = 'cod_barrio'
        elif 'cod_distrito' in lc:     col_rename[c] = 'cod_distrito'
    df.rename(columns=col_rename, inplace=True)
    mask_renta = df['indicador_nivel1'].astype(str).str.contains('Renta|renta', na=False, case=False)
    mask_neta  = df['indicador_nivel2'].astype(str).str.contains('Neta|neta|Net', na=False, case=False)
    renta_df   = df[mask_renta & mask_neta].copy()
    if len(renta_df) == 0:
        renta_df = df[mask_renta].copy()
    renta_df['año'] = pd.to_numeric(renta_df.get('año', pd.Series()), errors='coerce')
    anyo_max = renta_df['año'].max()
    renta_df = renta_df[renta_df['año'] == anyo_max].copy()
    renta_df['valor_num'] = pd.to_numeric(
        renta_df['valor_indicador'].astype(str)
        .str.replace('.', '', regex=False).str.replace(',', '.', regex=False),
        errors='coerce'
    )
    if 'cod_barrio' in renta_df.columns:
        renta_bar = (
            renta_df.dropna(subset=['cod_barrio', 'valor_num'])
            .assign(cod_barrio=lambda x: pd.to_numeric(x['cod_barrio'], errors='coerce'))
            .dropna(subset=['cod_barrio'])
        )
    else:
        renta_bar = pd.DataFrame()

    if len(renta_bar) >= 20:
        resultado = (
            renta_bar.groupby('cod_barrio')['valor_num']
            .mean().reset_index()
            .rename(columns={'valor_num': 'renta_neta', 'cod_barrio': 'cod_barrio_ref'})
        )
        nivel = 'barrio'
    else:
        renta_dist = (
            renta_df.dropna(subset=['cod_distrito', 'valor_num'])
            .assign(cod_distrito=lambda x: pd.to_numeric(x['cod_distrito'], errors='coerce'))
            .dropna(subset=['cod_distrito'])
        )
        resultado = renta_dist.groupby('cod_distrito')['valor_num'].mean().reset_index().rename(
            columns={'valor_num': 'renta_neta'})
        nivel = 'distrito'
    print(f'     ✓ Año {int(anyo_max)} | nivel: {nivel} | '
          f'rango: {resultado["renta_neta"].min():.0f}€–{resultado["renta_neta"].max():.0f}€')
    return resultado, nivel


def procesar_arbolado_distrito():
    print('\n  2e. Arbolado en parques (árboles por distrito)...')
    df = pd.read_csv('data/raw/arbolado.csv', encoding='latin-1', sep=';', low_memory=False)
    df = limpiar_columnas(df)
    col_distrito = next((c for c in df.columns if 'Distrito' in c and 'º' in c), df.columns[0])
    col_unidades = next((c for c in df.columns if 'nidades' in c or 'Unidades' in c), df.columns[3])
    df.rename(columns={col_distrito: 'cod_distrito', col_unidades: 'num_arboles'}, inplace=True)
    df = df.dropna(subset=['cod_distrito', 'num_arboles'])
    df['cod_distrito'] = pd.to_numeric(df['cod_distrito'], errors='coerce').astype('Int64')
    df['num_arboles']  = pd.to_numeric(df['num_arboles'],  errors='coerce')
    resultado = (
        df.dropna(subset=['cod_distrito', 'num_arboles'])
        .groupby('cod_distrito')['num_arboles'].sum().reset_index()
        .rename(columns={'num_arboles': 'total_arboles'})
    )
    print(f'     ✓ {len(resultado)} distritos | total: {resultado["total_arboles"].sum():,.0f} árboles')
    return resultado


def procesar_calidad_aire():
    """
    FIX v4: devuelve el DataFrame de estaciones con coordenadas para IDW,
    además de la media global como fallback.
    Intenta cargar coordenadas desde el CSV de estaciones; si no existe,
    usa las coordenadas embebidas del dataset histórico del portal.
    """
    print('\n  2f. Calidad del aire (NO₂ verano)...')
    df = pd.read_csv('data/raw/calidad_aire.csv', encoding='latin-1', sep=';', low_memory=False)
    df = limpiar_columnas(df)
    no2 = pivotear_formato_ancho(df, magnitud_cod=8, nombre_col='no2')
    if len(no2) == 0:
        print('     ⚠ Magnitud 8 no encontrada — usando valor de referencia 30 µg/m³')
        return pd.DataFrame(columns=['ESTACION', 'no2_verano', 'lon', 'lat']), 30.0

    verano = no2[no2['MES'].isin([6, 7, 8])]
    if len(verano) == 0:
        verano = no2
    por_estacion = (verano.groupby('ESTACION')['no2']
                    .mean().reset_index().rename(columns={'no2': 'no2_verano'}))
    media_global = por_estacion['no2_verano'].mean()
    print(f'     ✓ NO₂ medio: {media_global:.1f} µg/m³ ({len(por_estacion)} estaciones)')

    # Intentar enriquecer con coordenadas geográficas de las estaciones
    por_estacion = _enriquecer_coordenadas_aire(por_estacion, df)

    por_estacion.to_csv('data/processed/no2_estaciones.csv', index=False)
    return por_estacion, media_global


def _enriquecer_coordenadas_aire(por_estacion, df_medidas):
    """
    Añade columnas lon/lat a por_estacion.
    FIX: lee directamente del CSV de estaciones descargado (data/raw/estaciones_calidad_aire.csv)
    usando CODIGO_CORTO como clave de unión con ESTACION de las medidas.
    Fallback: diccionario hardcodeado de coordenadas conocidas.
    """
    # Fuente primaria: CSV de estaciones descargado (tiene columnas LONGITUD y LATITUD)
    ruta_est = 'data/raw/estaciones_calidad_aire.csv'
    if os.path.exists(ruta_est):
        try:
            df_est = pd.read_csv(ruta_est, encoding='latin-1', sep=';', low_memory=False)
            df_est = limpiar_columnas(df_est)
            # Normalizar nombre de columna clave (puede venir con BOM)
            for c in df_est.columns:
                if 'CODIGO' in c.upper() and 'CORTO' in c.upper():
                    df_est.rename(columns={c: 'CODIGO_CORTO'}, inplace=True)
                    break
            df_est['CODIGO_CORTO'] = pd.to_numeric(df_est['CODIGO_CORTO'], errors='coerce')
            # Seleccionar columnas de coordenadas
            lon_col = next((c for c in df_est.columns if c.upper() == 'LONGITUD'), None)
            lat_col = next((c for c in df_est.columns if c.upper() == 'LATITUD'), None)
            if lon_col and lat_col:
                coords_df = df_est[['CODIGO_CORTO', lon_col, lat_col]].copy()
                coords_df.columns = ['CODIGO_CORTO', 'lon', 'lat']
                coords_df['lon'] = pd.to_numeric(coords_df['lon'], errors='coerce')
                coords_df['lat'] = pd.to_numeric(coords_df['lat'], errors='coerce')
                por_estacion = por_estacion.copy()
                por_estacion['ESTACION_num'] = pd.to_numeric(por_estacion['ESTACION'], errors='coerce')
                por_estacion = por_estacion.merge(coords_df, left_on='ESTACION_num',
                                                   right_on='CODIGO_CORTO', how='left')
                por_estacion.drop(columns=['ESTACION_num', 'CODIGO_CORTO'], errors='ignore', inplace=True)
                n_geo = por_estacion['lon'].notna().sum()
                print(f'     ✓ {n_geo}/{len(por_estacion)} estaciones georreferenciadas (CSV estaciones)')
                return por_estacion
        except Exception as e:
            print(f'     ⚠ No se pudo leer CSV de estaciones: {e} — usando coordenadas embebidas')

    # Fallback: coordenadas hardcodeadas de las 24 estaciones fijas de Madrid
    COORDS_EST = {
        4:  (-3.712257, 40.423882),  8:  (-3.682316, 40.421553),
        11: (-3.677349, 40.451473),  16: (-3.639242, 40.440046),
        17: (-3.713317, 40.347147),  18: (-3.731836, 40.394782),
        24: (-3.747345, 40.419358),  27: (-3.580026, 40.476918),
        35: (-3.712535, 40.445041),  36: (-3.651685, 40.408434),
        38: (-3.712386, 40.466175),  39: (-3.651924, 40.372171),
        40: (-3.688833, 40.398107),  47: (-3.692148, 40.453585),
        48: (-3.774851, 40.512109),  49: (-3.676697, 40.494964),
        50: (-3.613141, 40.371444),  54: (-3.724866, 40.435294),
        55: (-3.712535, 40.445041),  56: (-3.710499, 40.396910),
        57: (-3.651924, 40.484400),  58: (-3.774851, 40.512109),
        59: (-3.606670, 40.461600),  60: (-3.682000, 40.415000),
    }
    lon_list, lat_list = [], []
    for _, row in por_estacion.iterrows():
        est_id = int(row['ESTACION']) if str(row['ESTACION']).isdigit() else -1
        coords = COORDS_EST.get(est_id, (None, None))
        lon_list.append(coords[0])
        lat_list.append(coords[1])

    por_estacion = por_estacion.copy()
    por_estacion['lon'] = lon_list
    por_estacion['lat'] = lat_list
    n_geo = por_estacion['lon'].notna().sum()
    print(f'     ✓ {n_geo}/{len(por_estacion)} estaciones georreferenciadas (coordenadas embebidas)')
    return por_estacion


def procesar_temperatura():
    """
    FIX v4: igual que calidad del aire — devuelve DataFrame con coordenadas
    para interpolación IDW.
    """
    print('\n  2g. Temperatura media verano...')
    df = pd.read_csv('data/raw/meteo.csv', encoding='latin-1', sep=';', low_memory=False)
    df = limpiar_columnas(df)
    temp = pivotear_formato_ancho(df, magnitud_cod=83, nombre_col='temp')
    if len(temp) == 0:
        temp = pivotear_formato_ancho(df, magnitud_cod=81, nombre_col='temp')
    if len(temp) == 0:
        print('     ⚠ Sin datos de temperatura — usando densidad como proxy')
        return pd.DataFrame(columns=['ESTACION', 'temp_verano', 'lon', 'lat']), None

    verano = temp[temp['MES'].isin([6, 7, 8])]
    if len(verano) == 0:
        verano = temp
    por_estacion = (verano.groupby('ESTACION')['temp']
                    .mean().reset_index().rename(columns={'temp': 'temp_verano'}))
    media_global = por_estacion['temp_verano'].mean()
    print(f'     ✓ Temperatura media: {media_global:.1f} °C')

    # FIX: leer coordenadas desde el CSV de estaciones meteo descargado
    ruta_est_meteo = 'data/raw/estaciones_meteo.csv'
    if os.path.exists(ruta_est_meteo):
        try:
            df_est_m = pd.read_csv(ruta_est_meteo, encoding='latin-1', sep=';', low_memory=False)
            df_est_m = limpiar_columnas(df_est_m)
            # Buscar columna clave de ID de estación
            # NOTA: 'CÓDIGO' puede quedar como 'CÁ\x93DIGO' tras limpiar_columnas(),
            # así que buscamos por 'CORTO' (siempre intacto) o por índice posicional.
            id_col = next((c for c in df_est_m.columns if 'CORTO' in c.upper()), None)
            if id_col is None:
                # Fallback: columna índice 1 (siempre es CÓDIGO_CORTO en este dataset)
                id_col = df_est_m.columns[1] if len(df_est_m.columns) > 1 else None
            lon_col = next((c for c in df_est_m.columns if c.upper() == 'LONGITUD'), None)
            lat_col = next((c for c in df_est_m.columns if c.upper() == 'LATITUD'), None)
            if id_col and lon_col and lat_col:
                df_est_m[id_col] = pd.to_numeric(df_est_m[id_col], errors='coerce')
                df_est_m['lon'] = pd.to_numeric(df_est_m[lon_col], errors='coerce')
                df_est_m['lat'] = pd.to_numeric(df_est_m[lat_col], errors='coerce')
                coords_m = df_est_m[[id_col, 'lon', 'lat']].rename(columns={id_col: 'ESTACION_num'})
                por_estacion = por_estacion.copy()
                por_estacion['ESTACION_num'] = pd.to_numeric(por_estacion['ESTACION'], errors='coerce')
                por_estacion = por_estacion.merge(coords_m, on='ESTACION_num', how='left')
                por_estacion.drop(columns=['ESTACION_num'], errors='ignore', inplace=True)
                n_geo = por_estacion['lon'].notna().sum()
                print(f'     ✓ {n_geo}/{len(por_estacion)} estaciones meteo georreferenciadas (CSV estaciones)')
                por_estacion.to_csv('data/processed/temp_estaciones.csv', index=False)
                return por_estacion, media_global
        except Exception as e:
            print(f'     ⚠ No se pudo leer CSV estaciones meteo: {e} — usando coordenadas embebidas')

    # Fallback: coordenadas hardcodeadas
    COORDS_METEO = {
        3: (-3.7167, 40.4180),  4: (-3.7025, 40.4530),  5: (-3.6528, 40.4784),
        6: (-3.7264, 40.3803),  7: (-3.7160, 40.4600),  8: (-3.7274, 40.3937),
        9: (-3.6832, 40.4459), 10: (-3.6901, 40.4562), 11: (-3.7193, 40.4037),
       12: (-3.7014, 40.4487), 13: (-3.7122, 40.4219), 16: (-3.6840, 40.4282),
       17: (-3.7052, 40.4180), 18: (-3.6946, 40.4564), 24: (-3.6924, 40.4210),
    }
    lon_list, lat_list = [], []
    for _, row in por_estacion.iterrows():
        est_id = int(row['ESTACION']) if str(row['ESTACION']).isdigit() else -1
        coords = COORDS_METEO.get(est_id, (None, None))
        lon_list.append(coords[0])
        lat_list.append(coords[1])

    por_estacion = por_estacion.copy()
    por_estacion['lon'] = lon_list
    por_estacion['lat'] = lat_list
    n_geo = por_estacion['lon'].notna().sum()
    print(f'     ✓ {n_geo}/{len(por_estacion)} estaciones meteo georreferenciadas (coordenadas embebidas)')
    por_estacion.to_csv('data/processed/temp_estaciones.csv', index=False)
    return por_estacion, media_global


# ──────────────────────────────────────────────────────────────────────────────
# BLOQUE 3 — CONSTRUCCIÓN DEL IVCU
# ──────────────────────────────────────────────────────────────────────────────

def construir_ivcu(gdf_barrios, vuln_ref, padron_bar, renta, renta_nivel,
                   arboles_dist, no2_estaciones, no2_global,
                   temp_estaciones, temp_global):
    print('\n' + '═' * 60)
    print('  BLOQUE 3 — CONSTRUCCIÓN DEL IVCU')
    print('═' * 60)

    ivcu = gdf_barrios.copy()
    ivcu['area_ha'] = ivcu['area_m2'] / 10_000

    # ── Clave de unión robusta ────────────────────────────────────────────────
    if 'COD_DISBAR' in ivcu.columns:
        ivcu['cod_join'] = pd.to_numeric(ivcu['COD_DISBAR'], errors='coerce').astype('Int64')
    elif 'cod_barrio' in ivcu.columns:
        ivcu['cod_join'] = pd.to_numeric(ivcu['cod_barrio'], errors='coerce').astype('Int64')
    else:
        ivcu['cod_join'] = (
            ivcu['cod_distrito'].astype(str).str.zfill(2) +
            ivcu.get('NUM_BAR', pd.Series(['0'] * len(ivcu))).astype(str).str.zfill(2)
        ).pipe(pd.to_numeric, errors='coerce').astype('Int64')

    # ── Padrón: unión barrio → imputa media de DISTRITO si falta ─────────────
    # FIX: el shapefile codifica cod_barrio como distrito*10+seq (ej: 202 = dist 20, barrio 2)
    # pero el padrón usa COD_DIST_BARRIO como distrito*100+seq (ej: 2002 = dist 20, barrio 2).
    # Convertimos la clave del shapefile al formato del padrón antes del merge.
    print('\n  Uniendo padrón...')
    ivcu['padron_key'] = (
        ivcu['cod_distrito'] * 100 +
        (ivcu['cod_join'] - ivcu['cod_distrito'] * 10)
    ).astype('Int64')
    ivcu = ivcu.merge(
        padron_bar[['cod_dist_barrio', 'pob_total', 'pct_mayores_65', 'cod_distrito_padron']],
        left_on='padron_key', right_on='cod_dist_barrio', how='left'
    )
    # Imputación por distrito (no global)
    for col in ['pob_total', 'pct_mayores_65']:
        n_nulos = ivcu[col].isna().sum()
        if n_nulos > 0:
            media_dist = ivcu.groupby('cod_distrito')[col].transform('mean')
            ivcu[col] = ivcu[col].fillna(media_dist)
            ivcu[col] = ivcu[col].fillna(ivcu[col].mean())  # fallback global
            print(f'     ⚠ {col}: {n_nulos} nulos → imputado por media de distrito')
    print(f'     ✓ {ivcu["pct_mayores_65"].notna().sum()}/{len(ivcu)} barrios con datos de padrón')

    # ── Renta ─────────────────────────────────────────────────────────────────
    print('\n  Uniendo renta...')
    if renta_nivel == 'barrio' and 'cod_barrio_ref' in renta.columns:
        ivcu = ivcu.merge(renta, left_on='cod_join', right_on='cod_barrio_ref', how='left')
    else:
        ivcu = ivcu.merge(renta, on='cod_distrito', how='left')
    n_renta = ivcu['renta_neta'].isna().sum()
    if n_renta > 0:
        media_dist_renta = ivcu.groupby('cod_distrito')['renta_neta'].transform('mean')
        ivcu['renta_neta'] = ivcu['renta_neta'].fillna(media_dist_renta)
        ivcu['renta_neta'] = ivcu['renta_neta'].fillna(ivcu['renta_neta'].mean())
        print(f'     ⚠ renta_neta: {n_renta} nulos → imputado por media de distrito')
    print(f'     ✓ {ivcu["renta_neta"].notna().sum()}/{len(ivcu)} barrios con datos de renta')

    # ── Arbolado ──────────────────────────────────────────────────────────────
    print('\n  Uniendo arbolado...')
    ivcu = ivcu.merge(arboles_dist, on='cod_distrito', how='left')
    ivcu['arboles_por_ha'] = (ivcu['total_arboles'] / ivcu['area_ha']).round(2)
    n_arb = ivcu['arboles_por_ha'].isna().sum()
    if n_arb > 0:
        ivcu['arboles_por_ha'] = ivcu['arboles_por_ha'].fillna(ivcu['arboles_por_ha'].mean())
        print(f'     ⚠ arboles_por_ha: {n_arb} nulos → media global')
    print(f'     ✓ {ivcu["arboles_por_ha"].notna().sum()}/{len(ivcu)} barrios con datos de arbolado')

    # ── NO₂ por IDW (FIX v4: valor único por barrio, no global) ──────────────
    print('\n  Interpolando NO₂ por IDW...')
    centros = ivcu[['lon', 'lat']].copy()
    no2_geo = no2_estaciones.dropna(subset=['lon', 'lat']) if len(no2_estaciones) > 0 else pd.DataFrame()
    if len(no2_geo) >= 3:
        ivcu['no2_verano'] = idw_interpolar(no2_geo, centros, 'no2_verano').round(2)
        print(f'     ✓ IDW NO₂ | rango barrios: '
              f'{ivcu["no2_verano"].min():.1f}–{ivcu["no2_verano"].max():.1f} µg/m³')
    else:
        print(f'     ⚠ Menos de 3 estaciones georreferenciadas — usando media global ({no2_global:.1f})')
        ivcu['no2_verano'] = no2_global

    # ── Temperatura por IDW (FIX v4: valor único por barrio) ─────────────────
    print('\n  Interpolando temperatura por IDW...')
    temp_geo = temp_estaciones.dropna(subset=['lon', 'lat']) if len(temp_estaciones) > 0 else pd.DataFrame()
    if len(temp_geo) >= 3 and temp_global is not None:
        ivcu['temp_verano'] = idw_interpolar(temp_geo, centros, 'temp_verano').round(2)
        print(f'     ✓ IDW Temp | rango barrios: '
              f'{ivcu["temp_verano"].min():.1f}–{ivcu["temp_verano"].max():.1f} °C')
    else:
        ivcu['temp_verano'] = temp_global if temp_global else 0
        print(f'     ⚠ Sin suficientes estaciones — usando media global')

    # ── Vulnerabilidad de referencia (FIX v4: join en 3 pasos) ───────────────
    print('\n  Uniendo vulnerabilidad de referencia...')
    # Paso 1: por código numérico
    ivcu = ivcu.merge(
        vuln_ref[['cod_barrio_vuln', 'nombre_barrio_norm', 'ranking_ref', 'ivcu_ref']],
        left_on='cod_join', right_on='cod_barrio_vuln', how='left'
    )
    n_sin_ref = ivcu['ranking_ref'].isna().sum()
    print(f'     Paso 1 (código numérico): {len(ivcu) - n_sin_ref}/{len(ivcu)} matches')

    # Paso 2: por nombre normalizado para los que no matchearon
    if n_sin_ref > 0 and 'nombre_barrio' in ivcu.columns:
        ivcu['nombre_barrio_norm_join'] = ivcu['nombre_barrio'].apply(normalizar_nombre)
        vuln_ref_nombre = vuln_ref[['nombre_barrio_norm', 'ranking_ref', 'ivcu_ref']].copy()
        vuln_ref_nombre = vuln_ref_nombre.rename(columns={
            'ranking_ref': 'ranking_ref_b', 'ivcu_ref': 'ivcu_ref_b'})

        ivcu = ivcu.merge(vuln_ref_nombre, left_on='nombre_barrio_norm_join',
                          right_on='nombre_barrio_norm', how='left', suffixes=('', '_nom'))
        mask_falta = ivcu['ranking_ref'].isna() & ivcu['ranking_ref_b'].notna()
        ivcu.loc[mask_falta, 'ranking_ref'] = ivcu.loc[mask_falta, 'ranking_ref_b']
        ivcu.loc[mask_falta, 'ivcu_ref']    = ivcu.loc[mask_falta, 'ivcu_ref_b']
        ivcu.drop(columns=[c for c in ivcu.columns if c.endswith('_b') or c == 'nombre_barrio_norm_join'],
                  errors='ignore', inplace=True)
        n_sin_ref2 = ivcu['ranking_ref'].isna().sum()
        print(f'     Paso 2 (nombre norm.):   {n_sin_ref - n_sin_ref2} adicionales matched')
        n_sin_ref = n_sin_ref2

    print(f'     ✓ Total referencia: {len(ivcu) - n_sin_ref}/{len(ivcu)} barrios vinculados')

    # ── Densidad y exposición al calor ────────────────────────────────────────
    ivcu['densidad_hab_ha']      = (ivcu['pob_total'] / ivcu['area_ha']).round(1)
    # La exposición al calor combina densidad + temperatura interpolada
    ivcu['exposicion_calor_raw'] = (
        normalizar_0_10(ivcu['densidad_hab_ha']) * 0.6 +
        normalizar_0_10(ivcu['temp_verano'])     * 0.4
    )

    # ── Normalización y cálculo del IVCU ─────────────────────────────────────
    print('\n  Calculando IVCU...')
    ivcu['n_exposicion_calor']    = normalizar_0_10(ivcu['exposicion_calor_raw'], invertir=False)
    ivcu['n_falta_verde']         = normalizar_0_10(ivcu['arboles_por_ha'],       invertir=True)
    ivcu['n_vulnerabilidad_soc']  = normalizar_0_10(ivcu['pct_mayores_65'],       invertir=False)
    ivcu['n_privacion_economica'] = normalizar_0_10(ivcu['renta_neta'],           invertir=True)
    ivcu['n_contaminacion_aire']  = normalizar_0_10(ivcu['no2_verano'],           invertir=False)

    ivcu['IVCU'] = (
        ivcu['n_exposicion_calor']    * PESOS_IVCU['exposicion_calor']    +
        ivcu['n_falta_verde']         * PESOS_IVCU['falta_verde']         +
        ivcu['n_vulnerabilidad_soc']  * PESOS_IVCU['vulnerabilidad_soc']  +
        ivcu['n_privacion_economica'] * PESOS_IVCU['privacion_economica'] +
        ivcu['n_contaminacion_aire']  * PESOS_IVCU['contaminacion_aire']
    ).round(3)

    # Clasificación por quintiles
    p20, p40, p60, p80 = (ivcu['IVCU'].quantile(q) for q in [0.20, 0.40, 0.60, 0.80])
    UMBRALES_IVCU.update({'p20': p20, 'p40': p40, 'p60': p60, 'p80': p80})

    def clasificar(v):
        if   v <= p20: return 'Muy bajo'
        elif v <= p40: return 'Bajo'
        elif v <= p60: return 'Moderado'
        elif v <= p80: return 'Alto'
        else:          return 'Crítico'

    ivcu['nivel_riesgo'] = ivcu['IVCU'].apply(clasificar)
    ivcu = ivcu.sort_values('IVCU', ascending=False).reset_index(drop=True)
    ivcu['ranking_ivcu'] = ivcu.index + 1

    print(f'\n  ✓ IVCU calculado para {len(ivcu)} barrios')
    print(f'     Rango: {ivcu["IVCU"].min():.2f} – {ivcu["IVCU"].max():.2f}')
    print(f'     Umbrales quintiles: ≤{p20:.2f} | ≤{p40:.2f} | ≤{p60:.2f} | ≤{p80:.2f}')
    print(f'\n  Distribución de niveles:')
    print(ivcu['nivel_riesgo'].value_counts().to_string())
    print(f'\n  Top 10 más vulnerables:')
    cols_print = [c for c in ['ranking_ivcu', 'nombre_barrio', 'nombre_distrito', 'IVCU', 'nivel_riesgo']
                  if c in ivcu.columns]
    print(ivcu[cols_print].head(10).to_string(index=False))

    return ivcu


# ──────────────────────────────────────────────────────────────────────────────
# BLOQUE 6 — CLUSTERING IA (K-MEANS + PCA)
# ──────────────────────────────────────────────────────────────────────────────

# Etiquetas interpretativas para cada clúster.
# Se asignan post-hoc ordenando los clústeres por la dimensión dominante en PCA.
ETIQUETAS_CLUSTER = {
    0: 'Perfil A — Calor y densidad',
    1: 'Perfil B — Privación económica',
    2: 'Perfil C — Vulnerabilidad social',
    3: 'Perfil D — Contaminación',
    4: 'Perfil E — Verde deficitario',
    5: 'Perfil F — Bajo riesgo general',
}

COLORES_CLUSTER = [
    '#e74c3c', '#e67e22', '#8e44ad',
    '#2980b9', '#27ae60', '#95a5a6',
]


def clustering_ia(ivcu, n_clusters=5):
    """
    K-Means sobre los 5 indicadores normalizados.
    Añade columnas 'cluster_id' y 'perfil_vulnerabilidad' al DataFrame.
    Exporta resumen de perfiles a CSV.
    Genera figura PCA como HTML embebible.

    Metodología:
    - Estandarización Z-score para que todos los indicadores tengan igual peso
    - K-Means con k=5 (un clúster por tipo de vulnerabilidad dominante);
      se usa k=6 si el índice de silueta mejora >0.02
    - PCA 2D para visualización e interpretación de los ejes
    - Los clústeres se etiquetan según la dimensión con mayor peso en PCA

    Parámetros
    ----------
    ivcu       : GeoDataFrame con columnas n_exposicion_calor … n_contaminacion_aire
    n_clusters : número de clústeres (por defecto 5)

    Devuelve
    --------
    ivcu con columnas 'cluster_id' y 'perfil_vulnerabilidad' añadidas
    """
    print('\n' + '═' * 60)
    print('  BLOQUE 6 — CLUSTERING IA (K-Means + PCA)')
    print('═' * 60)

    features = [
        'n_exposicion_calor',
        'n_falta_verde',
        'n_vulnerabilidad_soc',
        'n_privacion_economica',
        'n_contaminacion_aire',
    ]

    X = ivcu[features].fillna(ivcu[features].mean()).values

    # ── Estandarización ───────────────────────────────────────────────────────
    scaler = StandardScaler()
    X_std  = scaler.fit_transform(X)

    # ── Silueta informativa (no determina k) ──────────────────────────────────
    # Madrid tiene una vulnerabilidad climática relativamente homogénea entre
    # barrios: los índices de silueta son bajos (~0.22) para cualquier k,
    # lo que haría que la selección automática eligiera k=2.
    # Forzamos k=5 para obtener perfiles interpretativamente ricos, y
    # reportamos la silueta como hallazgo metodológico en la memoria.
    from sklearn.metrics import silhouette_score
    print('     Índices de silueta por k (informativo):')
    for k in range(2, 7):
        km_test = KMeans(n_clusters=k, random_state=42, n_init=20)
        labels_test = km_test.fit_predict(X_std)
        sil = silhouette_score(X_std, labels_test)
        print(f'       k={k} | silueta={sil:.3f}')
    print('     → k=5 forzado para perfiles interpretativamente significativos')

    mejor_k = 5  # forzado — ver nota metodológica arriba

    # ── K-Means final (k=5) ───────────────────────────────────────────────────
    km_final = KMeans(n_clusters=mejor_k, random_state=42, n_init=20)
    ivcu     = ivcu.copy()
    ivcu['cluster_id'] = km_final.fit_predict(X_std)

    # ── PCA 2D ────────────────────────────────────────────────────────────────
    pca    = PCA(n_components=2, random_state=42)
    X_pca  = pca.fit_transform(X_std)
    ivcu['pca1'] = X_pca[:, 0].round(3)
    ivcu['pca2'] = X_pca[:, 1].round(3)

    var_exp = pca.explained_variance_ratio_
    print(f'\n  PCA — varianza explicada: PC1={var_exp[0]:.1%} | PC2={var_exp[1]:.1%}')
    print(f'  Loadings PC1: {dict(zip(features, pca.components_[0].round(3)))}')
    print(f'  Loadings PC2: {dict(zip(features, pca.components_[1].round(3)))}')

    # ── Etiquetado interpretativo de perfiles ─────────────────────────────────
    # Las etiquetas se derivan de los centroides reales del K-Means sobre los
    # datos de Madrid (131 barrios). Cada clúster se nombra por su indicador
    # diferenciador dominante respecto a la media global, no por el máximo
    # absoluto (que sería siempre n_falta_verde dado que el 98% de barrios
    # tiene déficit de verde según la fuente de arbolado en parques históricos).
    centroides_df = ivcu.groupby('cluster_id')[features].mean()

    # Para cada clúster: indicador con mayor DESVIACIÓN sobre la media global
    medias_globales = ivcu[features].mean()
    perfil_map = {}
    etiquetas_por_desviacion = {
        'n_exposicion_calor':    'Alta privación económica y contaminación',
        'n_falta_verde':         'Verde abundante (parques y zonas forestales)',
        'n_vulnerabilidad_soc':  'Envejecimiento y déficit de verde',
        'n_privacion_economica': 'Renta baja y escasez de verde',
        'n_contaminacion_aire':  'Alta privación económica y contaminación',
    }
    # Etiquetas manuales definitivas derivadas del análisis de centroides:
    # C0 (IVCU~6.42): n_privacion_economica=8.0, n_contaminacion_aire=5.9 → alta privación+contaminación
    # C1 (IVCU~6.18): n_vulnerabilidad_soc=6.2, verde deficitario → envejecimiento
    # C2 (IVCU~4.58): todos los indicadores bajos → vulnerabilidad contenida
    # C3 (IVCU~5.19): n_privacion_economica=6.9, n_falta_verde=9.3 → renta baja y escasez de verde
    # C4 (IVCU~4.06): n_falta_verde=2.2 (único clúster con verde real) → zonas forestales
    ETIQUETAS_FIJAS = {
        # Se asignan en función del IVCU medio y perfil de cada clúster
        # Re-evaluamos en tiempo de ejecución por si el seed produce orden distinto
    }
    for cid in range(mejor_k):
        cent = centroides_df.loc[cid]
        ivcu_medio = ivcu[ivcu['cluster_id'] == cid]['IVCU'].mean()
        n_barrios  = int((ivcu['cluster_id'] == cid).sum())

        # Desviación de cada indicador respecto a la media global
        desv = cent - medias_globales
        # El indicador diferenciador es el de mayor desviación positiva
        indicador_dom = desv.idxmax()
        verde_val = cent['n_falta_verde']

        # Árbol de decisión para etiqueta significativa:
        # Orden deliberado: los criterios más discriminantes primero para
        # evitar que clústeres con perfil mixto caigan en ramas incorrectas.
        if verde_val < 4.0:
            # Único tipo de barrio con verde real (El Pardo, Casa de Campo…)
            etq = 'Verde abundante (parques y zonas forestales)'
        elif cent['n_privacion_economica'] >= 7.5 and cent['n_contaminacion_aire'] >= 5.0:
            # Alta privación + contaminación elevada: el clúster más crítico
            etq = 'Alta privación económica y contaminación'
        elif cent['n_falta_verde'] >= 9.0 and cent['n_privacion_economica'] >= 5.5 and cent['n_vulnerabilidad_soc'] < 5.0:
            # Déficit extremo de verde + privación moderada, sin envejecimiento dominante
            etq = 'Renta baja y escasez de verde'
        elif cent['n_vulnerabilidad_soc'] >= 5.5 and cent['n_privacion_economica'] >= 4.5:
            # Envejecimiento + privación económica significativa: perfil de alto riesgo
            etq = 'Envejecimiento y déficit de verde'
        else:
            # Indicadores globalmente moderados o bajos
            etq = 'Vulnerabilidad contenida'

        perfil_map[cid] = etq
        print(f'     Clúster {cid}: {etq} | IVCU medio={ivcu_medio:.2f} | n={n_barrios} barrios')

    ivcu['perfil_vulnerabilidad'] = ivcu['cluster_id'].map(perfil_map)

    # ── Resumen de perfiles → CSV ─────────────────────────────────────────────
    resumen = (
        ivcu.groupby('perfil_vulnerabilidad')[features + ['IVCU']]
        .mean().round(2)
        .sort_values('IVCU', ascending=False)
    )
    resumen['n_barrios'] = ivcu.groupby('perfil_vulnerabilidad').size()
    resumen.to_csv('data/processed/perfiles_clustering.csv', encoding='utf-8-sig')
    print(f'\n  ✓ data/processed/perfiles_clustering.csv exportado')

    # ── HTML de dispersión PCA embebible ──────────────────────────────────────
    _exportar_pca_html(ivcu, var_exp, perfil_map, mejor_k)

    return ivcu


def _exportar_pca_html(ivcu, var_exp, perfil_map, n_clusters):
    """Genera un HTML interactivo de dispersión PCA con tooltips."""

    puntos_js = []
    for _, row in ivcu.iterrows():
        cid    = int(row['cluster_id'])
        color  = COLORES_CLUSTER[cid % len(COLORES_CLUSTER)]
        perfil = row.get('perfil_vulnerabilidad', f'C{cid}')
        nombre = row.get('nombre_barrio', '')
        ivcu_v = float(row['IVCU'])
        p1     = float(row['pca1'])
        p2     = float(row['pca2'])
        puntos_js.append(
            f'{{x:{p1:.3f},y:{p2:.3f},color:"{color}",label:"{nombre}",'
            f'perfil:"{perfil}",ivcu:{ivcu_v:.3f}}}'
        )

    data_js     = '[' + ','.join(puntos_js) + ']'
    var1_pct    = f'{var_exp[0]:.1%}'
    var2_pct    = f'{var_exp[1]:.1%}'

    colores_leyenda = []
    for cid in range(n_clusters):
        colores_leyenda.append(
            f'{{"color":"{COLORES_CLUSTER[cid % len(COLORES_CLUSTER)]}","label":"{perfil_map[cid]}"}}'
        )
    leyenda_js = '[' + ','.join(colores_leyenda) + ']'

    html = f"""<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>PCA Clustering IVCU Madrid</title>
<style>
  body{{font-family:'Segoe UI',Arial,sans-serif;background:#f8f9fa;margin:0;padding:16px;}}
  h2{{font-size:16px;color:#1a1a2e;margin-bottom:4px;}}
  p.sub{{font-size:11px;color:#6b7280;margin:0 0 12px;}}
  #canvas-wrap{{position:relative;background:#fff;border:1px solid #e5e7eb;
               border-radius:10px;overflow:hidden;}}
  canvas{{display:block;}}
  #tooltip{{position:absolute;background:#1a1a2e;color:#fff;padding:8px 12px;
            border-radius:8px;font-size:11px;pointer-events:none;display:none;
            white-space:nowrap;box-shadow:0 4px 12px rgba(0,0,0,.2);}}
  .leyenda{{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px;}}
  .ley-item{{display:flex;align-items:center;gap:5px;font-size:11px;color:#374151;}}
  .ley-dot{{width:10px;height:10px;border-radius:50%;flex-shrink:0;}}
</style>
</head>
<body>
<h2>Perfiles de vulnerabilidad climática — PCA K-Means</h2>
<p class="sub">Cada punto es un barrio de Madrid. PC1 ({var1_pct} varianza) · PC2 ({var2_pct} varianza)</p>
<div id="canvas-wrap">
  <canvas id="c" width="700" height="440"></canvas>
  <div id="tooltip"></div>
</div>
<div class="leyenda" id="leyenda"></div>
<script>
const DATA    = {data_js};
const LEYENDA = {leyenda_js};
const canvas  = document.getElementById('c');
const ctx     = canvas.getContext('2d');
const tip     = document.getElementById('tooltip');
const W = canvas.width, H = canvas.height;
const PAD = 40;

const xs = DATA.map(d=>d.x), ys = DATA.map(d=>d.y);
const xMin=Math.min(...xs), xMax=Math.max(...xs);
const yMin=Math.min(...ys), yMax=Math.max(...ys);
const xR = xMax-xMin || 1, yR = yMax-yMin || 1;

function toCanvas(x, y) {{
  return [
    PAD + (x - xMin) / xR * (W - 2*PAD),
    H - PAD - (y - yMin) / yR * (H - 2*PAD)
  ];
}}

function draw() {{
  ctx.clearRect(0,0,W,H);
  ctx.fillStyle='#f9fafb'; ctx.fillRect(0,0,W,H);
  ctx.strokeStyle='#e5e7eb'; ctx.lineWidth=1;
  [0.25,0.5,0.75].forEach(t=>{{
    const gx = PAD + t*(W-2*PAD);
    const gy = PAD + t*(H-2*PAD);
    ctx.beginPath(); ctx.moveTo(gx,PAD); ctx.lineTo(gx,H-PAD); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(PAD,gy); ctx.lineTo(W-PAD,gy); ctx.stroke();
  }});
  DATA.forEach(d=>{{
    const [cx,cy] = toCanvas(d.x,d.y);
    ctx.beginPath();
    ctx.arc(cx,cy,5,0,2*Math.PI);
    ctx.fillStyle=d.color+'cc';
    ctx.fill();
    ctx.strokeStyle=d.color;
    ctx.lineWidth=0.8;
    ctx.stroke();
  }});
}}
draw();

const leyDiv = document.getElementById('leyenda');
LEYENDA.forEach(l=>{{
  const el = document.createElement('div');
  el.className='ley-item';
  el.innerHTML=`<div class="ley-dot" style="background:${{l.color}}"></div>${{l.label}}`;
  leyDiv.appendChild(el);
}});

canvas.addEventListener('mousemove', e=>{{
  const rect = canvas.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  let found = null;
  for(const d of DATA){{
    const [cx,cy] = toCanvas(d.x,d.y);
    if(Math.hypot(cx-mx,cy-my)<8){{ found=d; break; }}
  }}
  if(found){{
    tip.style.display='block';
    tip.style.left=(mx+12)+'px'; tip.style.top=(my-8)+'px';
    tip.innerHTML=`<b>${{found.label}}</b><br>${{found.perfil}}<br>IVCU: ${{found.ivcu.toFixed(3)}}`;
  }} else {{
    tip.style.display='none';
  }}
}});
canvas.addEventListener('mouseleave',()=>tip.style.display='none');
</script>
</body>
</html>"""

    with open('data/processed/pca_clustering.html', 'w', encoding='utf-8') as f:
        f.write(html)
    print('  ✓ data/processed/pca_clustering.html (visualización PCA interactiva)')


# ──────────────────────────────────────────────────────────────────────────────
# BLOQUE 4 — EXPORTACIÓN DE RESULTADOS
# ──────────────────────────────────────────────────────────────────────────────

def exportar_resultados(ivcu):
    print('\n' + '═' * 60)
    print('  BLOQUE 4 — EXPORTACIÓN DE RESULTADOS')
    print('═' * 60)

    cols_csv = [
        'cod_distrito', 'nombre_distrito', 'cod_barrio', 'nombre_barrio',
        'ranking_ivcu', 'IVCU', 'nivel_riesgo',
        'perfil_vulnerabilidad', 'cluster_id',
        'pct_mayores_65', 'renta_neta', 'arboles_por_ha',
        'densidad_hab_ha', 'no2_verano', 'temp_verano', 'pob_total', 'area_ha',
        'n_exposicion_calor', 'n_falta_verde', 'n_vulnerabilidad_soc',
        'n_privacion_economica', 'n_contaminacion_aire',
        'ranking_ref', 'ivcu_ref', 'pca1', 'pca2', 'lat', 'lon',
    ]
    cols_csv = [c for c in cols_csv if c in ivcu.columns]

    ivcu_df = ivcu[cols_csv].copy()
    ivcu_df.to_csv('data/processed/ivcu_barrios.csv', index=False, encoding='utf-8-sig')
    print(f'\n  ✓ data/processed/ivcu_barrios.csv ({len(ivcu_df)} filas)')

    ivcu_geo = ivcu[cols_csv + ['geometry']].copy()
    try:
        ivcu_utm = ivcu_geo.to_crs(epsg=25830)
        ivcu_utm.to_file('data/processed/ivcu_barrios.gpkg', driver='GPKG', layer='ivcu_barrios')
        print(f'  ✓ data/processed/ivcu_barrios.gpkg (EPSG:25830 — listo para ArcGIS Pro)')
    except Exception as e:
        print(f'  ⚠ No se pudo exportar GeoPackage: {e}')

    ivcu_wgs = ivcu_geo.to_crs(epsg=4326)
    ivcu_wgs.to_file('data/processed/ivcu_barrios.geojson', driver='GeoJSON')
    print(f'  ✓ data/processed/ivcu_barrios.geojson (WGS84)')

    return ivcu_df


# ──────────────────────────────────────────────────────────────────────────────
# BLOQUE 5 — HTML INTERACTIVO CON FOLIUM
# ──────────────────────────────────────────────────────────────────────────────

def generar_html_interactivo(ivcu):
    print('\n' + '═' * 60)
    print('  BLOQUE 5 — HTML INTERACTIVO')
    print('═' * 60)

    import folium

    p20 = UMBRALES_IVCU.get('p20', ivcu['IVCU'].quantile(0.20))
    p40 = UMBRALES_IVCU.get('p40', ivcu['IVCU'].quantile(0.40))
    p60 = UMBRALES_IVCU.get('p60', ivcu['IVCU'].quantile(0.60))
    p80 = UMBRALES_IVCU.get('p80', ivcu['IVCU'].quantile(0.80))

    def color_ivcu(v):
        if   v <= p20: return COLORES['Muy bajo']
        elif v <= p40: return COLORES['Bajo']
        elif v <= p60: return COLORES['Moderado']
        elif v <= p80: return COLORES['Alto']
        else:          return COLORES['Crítico']

    def hex_a_rgba(hex_color, alpha=0.12):
        h = hex_color.lstrip('#')
        r, g, b = tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
        return f'rgba({r},{g},{b},{alpha})'

    with open('data/processed/ivcu_barrios.geojson', 'r', encoding='utf-8') as f:
        geojson_data = json.load(f)

    m = folium.Map(
        location=[40.416775, -3.703790],
        zoom_start=11,
        tiles=None,
        prefer_canvas=True,
    )

    folium.TileLayer(
        tiles='https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png',
        attr='© <a href="https://carto.com/">CARTO</a>',
        name='Mapa base',
        control=False,
        max_zoom=19,
    ).add_to(m)

    folium.TileLayer(
        tiles='https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}{r}.png',
        attr='© <a href="https://carto.com/">CARTO</a>',
        name='Etiquetas',
        control=False,
        max_zoom=19,
        overlay=True,
        zindex=500,
    ).add_to(m)

    def estilo(feature):
        v = feature['properties'].get('IVCU', 0)
        return {'fillColor': color_ivcu(v), 'color': '#ffffff', 'weight': 0.6, 'fillOpacity': 0.82}

    def highlight(feature):
        return {'weight': 2.5, 'color': '#1a1a2e', 'fillOpacity': 0.95}

    def barra(val_norm, color):
        pct = min(max(val_norm / 10 * 100, 0), 100)
        return (
            f'<div style="background:#f0f0f0;border-radius:4px;height:6px;width:100%;margin-top:3px;">'
            f'<div style="background:{color};height:6px;border-radius:4px;width:{pct:.0f}%;"></div></div>'
        )

    def popup_html(feature):
        p        = feature['properties']
        nombre   = p.get('nombre_barrio',        'N/D')
        distrito = p.get('nombre_distrito',      'N/D')
        iv       = p.get('IVCU',                   0)
        riesgo   = p.get('nivel_riesgo',         'N/D')
        ranking  = p.get('ranking_ivcu',         'N/D')
        pct65    = p.get('pct_mayores_65',          0)
        renta    = p.get('renta_neta',              0)
        arb      = p.get('arboles_por_ha',          0)
        no2      = p.get('no2_verano',              0)
        dens     = p.get('densidad_hab_ha',         0)
        pob      = p.get('pob_total',               0)
        rank_ref = p.get('ranking_ref',          'N/D')
        perfil   = p.get('perfil_vulnerabilidad', 'N/D')
        n_calor  = p.get('n_exposicion_calor',      5)
        n_verde  = p.get('n_falta_verde',           5)
        n_soc    = p.get('n_vulnerabilidad_soc',    5)
        n_econ   = p.get('n_privacion_economica',   5)
        n_aire   = p.get('n_contaminacion_aire',    5)

        c  = color_ivcu(iv)
        cl = hex_a_rgba(c)

        indicadores = [
            ('🌡️ Exposición calor',    n_calor, '#e74c3c', f'{dens:.0f} hab/ha'),
            ('🌳 Déficit arbolado',    n_verde, '#27ae60', f'{arb:.1f} árb/ha'),
            ('👴 Vulnerab. social',    n_soc,   '#8e44ad', f'{pct65:.1f}% >65 años'),
            ('💶 Privación económica', n_econ,  '#e67e22', f'{renta:,.0f} €/año'),
            ('💨 NO₂ verano',          n_aire,  '#2980b9', f'{no2:.1f} µg/m³'),
        ]
        filas = ''.join(
            f'<tr><td style="padding:5px 0 2px;color:#555;font-size:11px;">{e}</td>'
            f'<td style="padding:5px 0 2px;text-align:right;color:#333;font-size:11px;font-weight:600;">{d}</td></tr>'
            f'<tr><td colspan="2" style="padding:0 0 6px;">{barra(v, col)}</td></tr>'
            for e, v, col, d in indicadores
        )

        return f'''
        <div style="font-family:'Inter','Segoe UI',Arial,sans-serif;
                    width:300px;border-radius:10px;overflow:hidden;
                    box-shadow:0 4px 20px rgba(0,0,0,.15);">
          <div style="background:{c};padding:14px 16px;">
            <div style="font-size:16px;font-weight:700;color:#fff;letter-spacing:-.3px;">{nombre}</div>
            <div style="font-size:11px;color:rgba(255,255,255,.8);margin-top:3px;
                        text-transform:uppercase;letter-spacing:.5px;">{distrito}</div>
          </div>
          <div style="background:{cl};padding:12px 16px;display:flex;
                      justify-content:space-between;align-items:center;
                      border-bottom:1px solid rgba(0,0,0,.07);">
            <div style="text-align:center;">
              <div style="font-size:30px;font-weight:800;color:{c};line-height:1;">{iv:.2f}</div>
              <div style="font-size:9px;color:#888;text-transform:uppercase;letter-spacing:.8px;margin-top:3px;">IVCU</div>
            </div>
            <div style="text-align:center;">
              <div style="font-size:18px;font-weight:700;color:#333;">#{ranking}</div>
              <div style="font-size:9px;color:#888;text-transform:uppercase;letter-spacing:.8px;margin-top:3px;">Ranking</div>
            </div>
            <div style="text-align:center;">
              <span style="background:{c};color:#fff;font-size:11px;font-weight:700;
                           padding:4px 10px;border-radius:20px;">{riesgo}</span>
              <div style="font-size:9px;color:#888;text-transform:uppercase;letter-spacing:.8px;margin-top:6px;">Nivel</div>
            </div>
          </div>
          <div style="background:#fff;padding:10px 16px 14px;">
            <div style="font-size:10px;color:#888;margin-bottom:6px;padding:3px 8px;
                        background:#f3f4f6;border-radius:4px;display:inline-block;">
              🤖 IA: {perfil}
            </div>
            <table style="width:100%;border-collapse:collapse;">{filas}</table>
            <div style="margin-top:8px;padding-top:8px;border-top:1px solid #f0f0f0;
                        font-size:10px;color:#aaa;text-align:right;">
              Ranking Ayto.: #{rank_ref} · Población: {int(pob):,}
            </div>
          </div>
        </div>'''

    folium.GeoJson(
        geojson_data,
        name='IVCU por barrio',
        style_function=estilo,
        highlight_function=highlight,
        tooltip=folium.GeoJsonTooltip(
            fields=['nombre_barrio', 'nombre_distrito', 'IVCU', 'nivel_riesgo', 'perfil_vulnerabilidad'],
            aliases=['Barrio', 'Distrito', 'IVCU', 'Nivel', 'Perfil IA'],
            localize=True, sticky=True,
            style=(
                'background:#1a1a2e;color:#fff;font-family:Inter,sans-serif;'
                'font-size:12px;padding:8px 12px;border-radius:6px;'
                'border:none;box-shadow:0 2px 8px rgba(0,0,0,.3);'
            ),
        ),
        popup=folium.GeoJsonPopup(
            fields=['nombre_barrio'], labels=False, parse_html=False, max_width=320,
        ),
    ).add_to(m)

    m.get_root().header.add_child(folium.Element(
        '<link rel="preconnect" href="https://fonts.googleapis.com">'
        '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet">'
    ))

    # ── Panel lateral ranking ─────────────────────────────────────────────────
    top20 = ivcu.nlargest(20, 'IVCU')
    filas_ranking = ''
    for _, row in top20.iterrows():
        c  = color_ivcu(row['IVCU'])
        nb = row.get('nombre_barrio',   'N/D')
        nd = row.get('nombre_distrito', '')
        iv = row['IVCU']
        rk = int(row['ranking_ivcu'])
        pf = row.get('perfil_vulnerabilidad', '')
        filas_ranking += (
            f'<tr>'
            f'<td style="padding:5px 8px;color:#9ca3af;font-size:11px;font-weight:600;width:24px;">{rk}</td>'
            f'<td style="padding:5px 4px;">'
            f'<div style="font-size:12px;font-weight:600;color:#f9fafb;">{nb}</div>'
            f'<div style="font-size:10px;color:#6b7280;">{nd}</div>'
            f'<div style="font-size:9px;color:#9ca3af;">🤖 {pf}</div></td>'
            f'<td style="padding:5px 8px;text-align:right;">'
            f'<span style="background:{c};color:#fff;padding:2px 8px;border-radius:12px;'
            f'font-size:11px;font-weight:700;">{iv:.2f}</span></td></tr>'
        )

    ivcu_vals = ivcu['IVCU']
    dist_n    = ivcu['nivel_riesgo'].value_counts()
    cuenta    = lambda n: int(dist_n.get(n, 0))

    barra_dist = ''.join(
        f'<div style="flex:{cuenta(n)};background:{COLORES[n]};height:6px;border-radius:3px;" '
        f'title="{n}: {cuenta(n)} barrios"></div>'
        for n in ['Muy bajo', 'Bajo', 'Moderado', 'Alto', 'Crítico'] if cuenta(n) > 0
    )
    etiquetas_dist = ''.join(
        f'<span style="font-size:9px;color:{COLORES[n]};font-weight:600;">{n[0]}:{cuenta(n)}</span>'
        for n in ['Muy bajo', 'Bajo', 'Moderado', 'Alto', 'Crítico'] if cuenta(n) > 0
    )

    panel_html = f'''
    <div id="panel" style="position:fixed;top:16px;left:16px;z-index:1000;
        background:#111827;color:#f9fafb;border-radius:14px;width:300px;
        box-shadow:0 8px 32px rgba(0,0,0,.4);
        font-family:'Inter','Segoe UI',Arial,sans-serif;
        display:flex;flex-direction:column;max-height:90vh;overflow:hidden;">
      <div style="padding:16px 18px 12px;border-bottom:1px solid #1f2937;">
        <div style="display:flex;justify-content:space-between;align-items:flex-start;">
          <div>
            <div style="font-size:13px;font-weight:800;letter-spacing:-.3px;color:#fff;">IVCU Madrid 2024</div>
            <div style="font-size:10px;color:#6b7280;margin-top:2px;">Índice Vulnerabilidad Climática Urbana</div>
          </div>
          <button onclick="togglePanel()" style="background:#1f2937;border:none;color:#9ca3af;
              border-radius:6px;padding:4px 8px;cursor:pointer;font-size:11px;">✕</button>
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px;">
          <div style="background:#1f2937;border-radius:8px;padding:8px 10px;">
            <div style="font-size:18px;font-weight:700;color:#f87171;">{ivcu_vals.max():.2f}</div>
            <div style="font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:.5px;margin-top:2px;">IVCU máx.</div>
          </div>
          <div style="background:#1f2937;border-radius:8px;padding:8px 10px;">
            <div style="font-size:18px;font-weight:700;color:#60a5fa;">{ivcu_vals.min():.2f}</div>
            <div style="font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:.5px;margin-top:2px;">IVCU mín.</div>
          </div>
          <div style="background:#1f2937;border-radius:8px;padding:8px 10px;">
            <div style="font-size:18px;font-weight:700;color:#a78bfa;">{ivcu_vals.mean():.2f}</div>
            <div style="font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:.5px;margin-top:2px;">Media</div>
          </div>
          <div style="background:#1f2937;border-radius:8px;padding:8px 10px;">
            <div style="font-size:18px;font-weight:700;color:#34d399;">{len(ivcu)}</div>
            <div style="font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:.5px;margin-top:2px;">Barrios</div>
          </div>
        </div>
        <div style="margin-top:10px;display:flex;gap:4px;">{barra_dist}</div>
        <div style="display:flex;justify-content:space-between;margin-top:4px;">{etiquetas_dist}</div>
      </div>
      <div style="overflow-y:auto;flex:1;padding:4px 0;">
        <div style="padding:8px 18px 4px;font-size:10px;color:#4b5563;
                    text-transform:uppercase;letter-spacing:.8px;font-weight:600;">
          Top 20 — Más vulnerables
        </div>
        <table style="width:100%;border-collapse:collapse;">{filas_ranking}</table>
      </div>
      <div style="padding:10px 18px;border-top:1px solid #1f2937;
                  font-size:9px;color:#4b5563;text-align:center;">
        Fuente: datos.madrid.es · Premios Reutilización 2026
      </div>
    </div>
    <button onclick="togglePanel()" id="panel-btn" style="display:none;
        position:fixed;top:16px;left:16px;z-index:1000;
        background:#111827;color:#fff;border:none;border-radius:10px;
        padding:10px 16px;cursor:pointer;font-size:13px;font-weight:700;
        box-shadow:0 4px 16px rgba(0,0,0,.3);
        font-family:'Inter','Segoe UI',Arial,sans-serif;">
      📊 Ver ranking
    </button>
    <script>
      function togglePanel() {{
        var p = document.getElementById('panel');
        var b = document.getElementById('panel-btn');
        if (p.style.display === 'none') {{ p.style.display = 'flex'; b.style.display = 'none'; }}
        else {{ p.style.display = 'none'; b.style.display = 'block'; }}
      }}
    </script>'''

    m.get_root().html.add_child(folium.Element(panel_html))

    # ── Leyenda ───────────────────────────────────────────────────────────────
    items_leyenda = [
        ('Crítico',  COLORES['Crítico'],  f'> {p80:.2f}'),
        ('Alto',     COLORES['Alto'],     f'{p60:.2f} – {p80:.2f}'),
        ('Moderado', COLORES['Moderado'], f'{p40:.2f} – {p60:.2f}'),
        ('Bajo',     COLORES['Bajo'],     f'{p20:.2f} – {p40:.2f}'),
        ('Muy bajo', COLORES['Muy bajo'], f'≤ {p20:.2f}'),
    ]
    items_html = ''.join(
        f'<div style="display:flex;align-items:center;gap:8px;">'
        f'<div style="width:14px;height:14px;border-radius:3px;background:{col};flex-shrink:0;"></div>'
        f'<span style="font-size:11px;color:#374151;flex:1;">{etq}</span>'
        f'<span style="font-size:10px;color:#9ca3af;">{rng}</span></div>'
        for etq, col, rng in items_leyenda
    )

    leyenda_html = f'''
    <div style="position:fixed;bottom:24px;right:16px;z-index:1000;
        background:#fff;border-radius:12px;padding:14px 16px;
        box-shadow:0 4px 20px rgba(0,0,0,.15);
        font-family:'Inter','Segoe UI',Arial,sans-serif;min-width:210px;">
      <div style="font-size:11px;font-weight:700;color:#111827;margin-bottom:8px;
                  padding-bottom:6px;border-bottom:1px solid #f3f4f6;
                  text-transform:uppercase;letter-spacing:.5px;">🌡️ Vulnerabilidad climática</div>
      <div style="font-size:9px;color:#9ca3af;margin-bottom:8px;">Clasificación por quintiles · 131 barrios</div>
      <div style="display:flex;flex-direction:column;gap:5px;">{items_html}</div>
    </div>'''

    m.get_root().html.add_child(folium.Element(leyenda_html))

    # ── Título ────────────────────────────────────────────────────────────────
    titulo_html = '''
    <div style="position:fixed;top:16px;left:50%;transform:translateX(-50%);
        z-index:999;pointer-events:none;
        font-family:'Inter','Segoe UI',Arial,sans-serif;text-align:center;">
      <div style="background:rgba(255,255,255,0.95);border-radius:10px;
                  padding:8px 20px;backdrop-filter:blur(8px);
                  box-shadow:0 2px 12px rgba(0,0,0,.12);">
        <div style="font-size:14px;font-weight:800;color:#111827;letter-spacing:-.3px;">
          Índice de Vulnerabilidad Climática Urbana (IVCU)
        </div>
        <div style="font-size:10px;color:#6b7280;margin-top:2px;">
          131 barrios de Madrid · datos.madrid.es · Premios Reutilización 2026
        </div>
      </div>
    </div>'''

    m.get_root().html.add_child(folium.Element(titulo_html))

    ruta_html = 'ivcu_madrid_interactivo.html'
    m.save(ruta_html)
    print(f'\n  ✓ {ruta_html} generado')
    print(f'     Ábrete en cualquier navegador — no necesita servidor web')

    return ruta_html


# ──────────────────────────────────────────────────────────────────────────────
# PIPELINE PRINCIPAL
# ──────────────────────────────────────────────────────────────────────────────

def main():
    print('\n' + '═' * 60)
    print('  IVCU MADRID v4 — Índice de Vulnerabilidad Climática Urbana')
    print('  Premios de Reutilización de Datos 2026')
    print('  Ayuntamiento de Madrid · datos.madrid.es')
    print('═' * 60)

    # ── Bloque 1: Descarga ────────────────────────────────────────────────────
    descargar_todos()

    # ── Bloque 2: Procesamiento ───────────────────────────────────────────────
    print('\n' + '═' * 60)
    print('  BLOQUE 2 — PROCESAMIENTO DE FUENTES')
    print('═' * 60)

    gdf_barrios                    = procesar_barrios_shapefile()
    vuln_ref                       = procesar_vulnerabilidad_referencia()
    padron_bar                     = procesar_padron_barrio()
    renta, nivel                   = procesar_renta_barrio()
    arboles_dist                   = procesar_arbolado_distrito()
    no2_estaciones, no2_global     = procesar_calidad_aire()
    temp_estaciones, temp_global   = procesar_temperatura()

    # ── Bloque 3: IVCU ───────────────────────────────────────────────────────
    ivcu = construir_ivcu(
        gdf_barrios, vuln_ref, padron_bar, renta, nivel,
        arboles_dist,
        no2_estaciones, no2_global,
        temp_estaciones, temp_global,
    )

    # ── Bloque 6: Clustering IA ───────────────────────────────────────────────
    ivcu = clustering_ia(ivcu)

    # ── Bloque 4: Exportar ───────────────────────────────────────────────────
    exportar_resultados(ivcu)

    # ── Bloque 5: HTML interactivo ────────────────────────────────────────────
    generar_html_interactivo(ivcu)

    # ── Descargas automáticas en Colab ────────────────────────────────────────
    try:
        from google.colab import files
        print('\n  Iniciando descargas automáticas en Colab...')
        for f in [
            'ivcu_madrid_interactivo.html',
            'data/processed/ivcu_barrios.csv',
            'data/processed/ivcu_barrios.gpkg',
            'data/processed/perfiles_clustering.csv',
            'data/processed/pca_clustering.html',
        ]:
            if os.path.exists(f):
                files.download(f)
        print('  ✓ Descargas iniciadas en el navegador')
    except ImportError:
        print('\n  → Entorno local detectado.')
        print('    Abre ivcu_madrid_interactivo.html en el navegador.')

    # ── Resumen final ─────────────────────────────────────────────────────────
    print('\n' + '═' * 60)
    print('  RESUMEN — Ficheros generados')
    print('═' * 60)
    ficheros = [
        ('ivcu_madrid_interactivo.html',            '⭐ MAPA INTERACTIVO — abrir en navegador'),
        ('data/processed/ivcu_barrios.csv',         'CSV con IVCU, perfiles IA y coordenadas IDW'),
        ('data/processed/ivcu_barrios.gpkg',        'GeoPackage EPSG:25830 — ArcGIS Pro'),
        ('data/processed/ivcu_barrios.geojson',     'GeoJSON WGS84'),
        ('data/processed/perfiles_clustering.csv',  '🤖 Resumen K-Means por perfil'),
        ('data/processed/pca_clustering.html',      '🤖 Visualización PCA interactiva'),
        ('data/processed/no2_estaciones.csv',       'NO₂ por estación con coordenadas IDW'),
        ('data/processed/temp_estaciones.csv',      'Temperatura por estación con coordenadas IDW'),
    ]
    for ruta, desc in ficheros:
        existe = '✓' if os.path.exists(ruta) else '✗'
        tam = f'{os.path.getsize(ruta)/1024:.0f} KB' if os.path.exists(ruta) else 'no generado'
        print(f'  {existe} {ruta:<50} {tam:>8}   {desc}')

    print('\n' + '═' * 60)
    print('  Script completado. IVCU Madrid v4')
    print('  Para ArcGIS Pro: importa ivcu_barrios.gpkg')
    print('  Para el mapa:    abre ivcu_madrid_interactivo.html')
    print('  Para el análisis IA: abre pca_clustering.html')
    print('═' * 60)


if __name__ == '__main__':
    main()
